### ISSUE TITLE
New f1 textures

### ISSUE THREAD

**Issue by miniesda** [JdeRobot/RoboticsInfrastructure#257]
New chasis textures (re0_main.png) for the f1 model
![53bb186e-2247-44ca-a84c-0b6dafe04bd2](https://github.com/JdeRobot/RoboticsInfrastructure/assets/63803821/c6d8211a-cd72-4b13-a15a-0ef60980b9a5)
![a14f5030-8592-4df1-996d-99ae7994be92](https://github.com/JdeRobot/RoboticsInfrastructure/assets/63803821/48c5a619-ced5-4467-b494-eb896f5a15f6)
#256

**Comment by jmplaza** [comment]
Fixed in #256
