### ISSUE TITLE
[Humble] Missing manager.py in RADI 4.4.0

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsInfrastructure#258]
Hi, during testing the recently pushed RADI 4.4.0 I am facing this particular issue:

![image](https://github.com/JdeRobot/RoboticsInfrastructure/assets/40732709/5f4679db-c2fe-4b90-a8d1-78c47191e130)

with -d flag and running entrypoint.sh the exercises do not come to ready state.
![image](https://github.com/JdeRobot/RoboticsInfrastructure/assets/40732709/bc1712dc-dabd-4d58-9a0b-0bd8b2febddc)

![image](https://github.com/JdeRobot/RoboticsInfrastructure/assets/40732709/5e5700f8-42cb-413a-9917-91046552b859)

**Comment by ReyDoran** [comment]
Hi, sorry I think it's due to a mistake I made on entrypoint.sh while uploading the image. Could you please retry downloading the RADI 4.4.0?

**Comment by pawanw17** [comment]
Hi @ReyDoran Fixed. Thanks!
