### ISSUE TITLE
[Humble] Follow Line RR The track doesn't change.

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsInfrastructure#263]
The Track options have no effect.

![image](https://github.com/JdeRobot/RoboticsInfrastructure/assets/40732709/496ad7dd-1959-4b22-8d36-a96fd98027ac)

![image](https://github.com/JdeRobot/RoboticsInfrastructure/assets/40732709/995de75b-78ee-47a3-aff4-f4be941b669c)

Issue is seen on RADI 4.4.1

**Comment by ReyDoran** [comment]
Solved in Robotics Academy by [PR 2095](https://github.com/JdeRobot/RoboticsAcademy/pull/2095), will be available on the upcoming RADI-4.4.4
