### ISSUE TITLE
New drone interface for Humble

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsInfrastructure#308]
It will replace DroneWrapper from ROS Noetic. Requirements should be extracted from exercise expected [Robot API](http://jderobot.github.io/RoboticsAcademy/exercises/Drones/rescue_people#robot-api).

It should use [aerostack2 drone interface](https://github.com/aerostack2/aerostack2/blob/main/as2_python_api/as2_python_api/drone_interface_base.py) without behaviors in order to have a better performance. Instead behaviors, motion reference handlers should be used directly.

**Comment by pariaspe** [comment]
Done in #307
