### ISSUE TITLE
[Humble] Duplicate worlds in Custom Robots and RA exercise folders

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsInfrastructure#315]

**Comment by jmplaza** [comment]
Good point!

I think all the worlds should be moved here and removed from [RoboticsAcademy repo](https://github.com/JdeRobot/RoboticsAcademy). This way they are also available to other applications such as [VisualCircuit](https://github.com/JdeRobot/VisualCircuit) or [BehaviorTrees](https://github.com/JdeRobot/BehaviorTrees).

**Comment by ango1994** [comment]
Closed on #332
