### ISSUE TITLE
[Humble] RADI import errors on run

### ISSUE THREAD

**Issue by ReyDoran** [JdeRobot/RoboticsInfrastructure#334]
Launching a Humble RADI generated with build.sh script produces this output 
`Traceback (most recent call last):
  File "//RoboticsAcademy/src/manager/manager/manager.py", line 17, in <module>
    from src.manager.manager.launcher.launcher_engine import LauncherEngine
ModuleNotFoundError: No module named 'src'
BASE_DIR /RoboticsAcademy
`

**Comment by pawanw17** [comment]
The Dockerfile used needs to have
https://github.com/JdeRobot/RoboticsAcademy/blob/4429a55fb0fca30ac338bec9d4cea3c9fa16f563/scripts/mini_RADI/Dockerfile.mini_humble#L73C1-L73C19
