### ISSUE TITLE
Optimized exercises

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsInfrastructure#395]
- [X] Global Navigation
- [X] Obstacle Avoidance
- [x] Basic vacuum cleaner
- [X] Follow Line
- [x] Autoparking
- [x]  Follow person
- [x]  Localized vacuum cleaner
- [x]  Rescue people
- [x] Amazon Warehouse
- [x]  Montecarlo laser loc
- [x] 3D reconstruction

**Comment by javizqh** [comment]
Same as https://github.com/JdeRobot/RoboticsAcademy/issues/2570

**Comment by pawanw17** [comment]
Closed with v5.2.3 release.
