### ISSUE TITLE
Create a similar python package to hal_interfaces but for GUI

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsInfrastructure#420]
Create a similar python package to hal_interfaces but for GUI so that the amount of copy code decreases

**Comment by jmplaza** [comment]
I see the convenience of this, but as this is very specific to RoboticsAcademy, maybe we could create those python packages but move them (even with hal_interfaces too) to RA repo...

**Comment by javizqh** [comment]
Yes, they could be moved. For now I will make it the same as hal_interfaces and when we move that one in the future we could move both
